# Generated by Django 3.2.14 on 2022-11-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Тег рецепта', 'verbose_name_plural': 'Теги рецепта'},
        ),
    ]
