# Generated by Django 3.2.14 on 2022-11-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_and_author_can_not_be_equal',
        ),
    ]
