# Generated by Django 3.2.14 on 2022-11-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_follow_user_and_author_can_not_be_equal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-id'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
